# Generated by Django 4.2.3 on 2023-07-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pets_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
